-- local awful = require("awful")
-- local naughty = require("naughty")
--  
-- -- Notification will be displayed if you press X.
-- -- Notification WON'T be displayed if you release Y (read comments).
-- -- Grabber will quit when you press Q or if it doesn't receive input for 5 seconds.
-- local grabber = awful.keygrabber {
--     keybindings = {
--         awful.key {
--             key = "x",
--             modifiers = {},
--             on_press = function()
--                 naughty.notification { message = "You pressed X" }
--             end,
--         },
--         awful.key {
--             key = "y",
--             modifiers = {},
--             on_release = function() -- `on_release` doesn't actually work, probably a bug
--                 naughty.notification { message = "You released Y" }
--             end,
--         },
--     },
--     
--     autostart = true, -- start the grabber immidately, otherwise call `grabber:start()` to start it
--     timeout = 5, -- stop the grabber if it doesn't receive any input for 5 seconds
--     stop_key = "q" -- stop the grabber if this key is pressed
-- }
--
-- -- Notification will be displayed if you press any key.
-- -- Special notification will be displayed if you press either X or Y.
-- -- Grabber will quit if you release Q or if it doesn't receive input for 5 seconds.
-- local grabber = awful.keygrabber {
-- 	keybindings = {
-- 		awful.key {
-- 			key = "x",
-- 			modifiers = {},
-- 			on_press = function()
-- 				naughty.notification { message = "You pressed X" }
-- 			end,
-- 		},
-- 		awful.key {
-- 			key = "y",
-- 			modifiers = {},
-- 			on_release = function() -- `on_release` doesn't actually work, probably a bug
-- 				naughty.notification { message = "You released Y" }
-- 			end,
-- 		},
-- 	},
-- 	
-- 	autostart = true, -- start the grabber immidately, otherwise call `grabber:start()` to start it
-- 	timeout = 5, -- stop the grabber if it doesn't receive any input for 5 seconds
-- 	stop_key = "q" -- stop the grabber if this key is pressed
-- }
--
-- -- Notification will be displayed if you press X.
-- -- A different notification will be displayed if you release Y.
-- -- Grabber will quit if you press Q or if it doesn't receive input for 5 seconds.
-- -- local awful = require("awful")
-- local notification = require("naughty.notification")
--
-- local grabber = awful.keygrabber {
-- 	autostart = true,
-- 	timeout = 5, -- stop the grabber if it doesn't receive any input for 5 seconds
-- }
--
-- grabber:connect_signal("q::press", function()
-- 	grabber:stop()
-- end)
--
-- grabber:connect_signal("x::press", function()
-- 	notification { message = "You pressed X" }
-- end)
--
-- grabber:connect_signal("y::release", function()
-- 	notification { message = "You released Y" }
-- end)
